NetworkInfo new field: rpc_url
TheDotflow/dotflow-ink pull request #66
Opened 2023-06-29 17:05 UTC by Szegoo

We need to know the RPC URL of the blockchains we intend to communicate with.

2023-06-30 00:26 UTC, cuteolaf requested changes

2023-06-30 00:26 UTC, cuteolaf commented on contracts/identity/lib.rs
> +const NETWORK_RPC_URL_LIMIT: usize = 32;
looks too short

2023-07-01 10:38 UTC, Szegoo commented
Let's not merge this yet, we might actually need the `name` field.

2023-07-02 07:23 UTC, Szegoo commented
@cuteolaf It is possible to get the name and the parachainId of a network from an RPC: https://substrate.stackexchange.com/a/9093/2163

2023-07-03 13:09 UTC, cuteolaf approved these changes

2023-07-03 13:10 UTC, merged